version: '3'
services:
  app:
    build:  
      context: ./
    volumes:
      - .:/go/src/app:rw
    ports:
      -"8080:8080"
    container_name: go-mysql-docker
  db:
    image: mysql:latest
    ports:
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    container_name: go_mysql_docker
    command: 
      - --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD-SHEL", "echo 'select 1' |mysql -uroot -ppassword --silent"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s